### PR TITLE
build docker image 

### PR DESCRIPTION
**Pull request by kvchitrapu**
1. Builds vidyut-py
2. Runs unit tests

## Usage
```
$ make docker-start
...<snipped all lines>...
Successfully built 184c31caec55
Successfully tagged vidyut-py:v0.1-main-e1e1af6
Successfully tagged vidyut-py-rel:latest
Vidyut-py Image    : ✔ (vidyut-py:v0.1-main-e1e1af6, vidyut-py-rel:latest)
```

## Testing
```
$ docker run -it --entrypoint /bin/sh vidyut-py-rel:latest 
$ . /usr/src/env/bin/activate
$  pip install click indic_transliteration
# copied a test script
(env) # python /root/pada-transliterated.py -f /root/sloka.txt
Sloka in None: शुक्लाम्बरधरं विष्णुं शशिवर्णं चतुर्भुजम् प्रसन्नवदनं ध्यायेत् सर्वविघ्नोपशान्तये

Sloka in sanscript.SLP1: SuklAmbaraDaraM vizRuM SaSivarRaM caturBujam prasannavadanaM DyAyet sarvaviGnopaSAntaye
 
Pada cheda:
	Token<(text='Sukla', lemma='Sukla', info=Pada(pos=PartOfSpeech.Subanta, pratipadika=Pratipadika(text='Sukla'), linga=Linga.Pum, is_purvapada=True))>
	...
	Token<(text='DyAyet', lemma='', info=Pada(None))>
	Token<(text='sarva', lemma='sarva', info=Pada(pos=PartOfSpeech.Subanta, pratipadika=Pratipadika(text='sarva'), linga=Linga.Pum, is_purvapada=True))>
	Token<(text='viGna', lemma='viGna', info=Pada(pos=PartOfSpeech.Subanta, pratipadika=Pratipadika(text='viGna'), linga=Linga.Pum, is_purvapada=True))>
	Token<(text='upaSAntaye', lemma='upaSAnti', info=Pada(pos=PartOfSpeech.Subanta, pratipadika=Pratipadika(text='upaSAnti'), linga=Linga.Stri, vibhakti=Vibhakti.V4, vacana=Vacana.Eka, is_purvapada=False))>
(env) # 
```

### CODE REVIEW

**Comment by kvchitrapu** [comment]
@akprasad, the container builds and runs unit tests. Your purpose might be different. We can change the Dockerfile to match your needs.

**Comment by akprasad** [comment]
Thanks -- why is this PR part of this repo as opposed to ambuda-org/ambuda?

**Comment by kvchitrapu** [comment]
Intially I thought you wanted here as we didn't talk about the repo. Later, I realized you were talking about ambuda. Anyways, the dockerfile enables zero setup cost for build and test of the vidyut-py.

BTW, I just pushed the quiet mode as well. See https://github.com/ambuda-org/ambuda/pull/442/files#diff-19930a397854a885e9636fba0b43ff3db46f27cd7573b8e11ae766f356b686ebR62

**Comment by kvchitrapu** [comment]
> would be nice to see build logs -- detailed is fine, as this is for developers and it helps build confidence that the process is working.


 Latest commit added:
### Vidyut data 
```
# inside the webapp container
root@63227e694da4:/app# ls $VIDYUT_DATA_DIR
data-0.2.0.zip	emissions.csv	  padas.fst	    sandhi-rules.csv  vidyut_is_here
dhatus.csv	lemma-counts.csv  pratipadikas.csv  transitions.csv
```

### Verbose mode
```
# from repo top dir
$ make docker-start
> Ambuda build is in progress. Expect it to take 2-5 minutes.
---------------------
[+] Building 0.4s (35/35) FINISHED                                                                             
 => [internal] load build definition from Dockerfile.final                                                0.0s
 => => transferring dockerfile: 43B                                                                       0.0s
 => [internal] load .dockerignore                                                                         0.0s
 => => transferring context: 34B                                                                          0.0s
 => [internal] load metadata for docker.io/library/python:3.9.13-slim-buster                              0.3s
 => [internal] load build context               
...
ambuda-local-dbsetup-1  | Database setup complete.
ambuda-local-dbsetup-1  | Vidyut data found!
ambuda-local-dbsetup-1  | Vidyut data setup complete
ambuda-local-dbsetup-1 exited with code 0
Ambuda Database : ✔ 
WARN[0000] Found orphan containers ([ambuda-local-dbsetup-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Running 3/3
 ⠿ Container ambuda-local-redis-1       Started                                                           0.3s
 ⠿ Container ambuda-local-ambuda-web-1  Started                                                           0.3s
 ⠿ Container ambuda-local-celery-1      Started                                                           0.4s
Ambuda WebApp   : ✔ 
Ambuda URL      : http://0.0.0.0:5090
---------------------
To stop, run "make docker-stop".
 ```
### Quiet mode
 ```
# from repo top dir
$ make Q=1 docker-start
> Ambuda build is in progress. Expect it to take 2-5 minutes.
---------------------
Ambuda Image    : ✔ (ambuda:v0.1-main-8af5241, ambuda-rel:latest)
Ambuda Database : ✔ 
Ambuda WebApp   : ✔ 
Ambuda URL      : http://0.0.0.0:5090
---------------------
To stop, run "make docker-stop".
```

**Comment by akprasad** [comment]
Thanks -- let's follow up on ambuda-org/ambuda . I think Docker is too much for this repo, but I would love to reuse this work there if it makes sense.

Note that for now, I intend to use whatever version of `vidyut` is on PyPI and reuse any native binaries there. So for now, we don't need a separate Rust binary as part of the image.

**Pull request closed without merging**
